# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - disasterpredictionapi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://kittakornazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6027d42fe38b4bdbb095f4a30ec57f07 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_515e7d69681d41878cfeca25b98e7bd2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kittakornazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6027d42fe38b4bdbb095f4a30ec57f07 }}/kittakornazure/disasterpredictionapi:${{ github.sha }}
        file: ./DisasterPrediction.Api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'disasterpredictionapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_02192c052290479d85f2941e3551ca3e }}
        images: 'kittakornazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6027d42fe38b4bdbb095f4a30ec57f07 }}/kittakornazure/disasterpredictionapi:${{ github.sha }}'